### PR TITLE
Fix autofill

### LINKED ISSUE #386: Database UIs do not work with host 0.0.0.0
Platform: macOS
CLI version: 8.13.1

Here's my `firebase.json`:
```
{
  "emulators": {
    "database": {
      "host": "0.0.0.0",
      "port": 9001
    },
    "firestore": {
      "host": "0.0.0.0",
      "port": 9002
    },
    "functions": {
      "host": "0.0.0.0",
      "port": 9003
    },
    "ui": {
      "enabled": true
    }
  }
}
```

Here's what I see in the RTDB UI:
Screen Shot 2020-10-23 at 2 51 54 PM

In the UI I see 404s and also this error:
```
io-6de156f3.js:111 TypeError: Cannot read property 'hostAndPort' of undefined
    at sagas.ts:129
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at p (redux-saga-core.esm.js:1157)
    at u (redux-saga-core.esm.js:1251)
    at k.<computed> (redux-saga-core.esm.js:731)
    at redux-saga-core.esm.js:1203
    at v (redux-saga-core.esm.js:1271)
    at p (redux-saga-core.esm.js:1161)
g @ io-6de156f3.js:111
```

In the Firestore UI it appears to be working but I see these errors in the Chrome dev console:
Screen Shot 2020-10-23 at 2 56 28 PM

### PR DESCRIPTION
**Pull request by NothingEverHappens**
fix(auth): Auth Emulator UI shouting to the console when disabled
fix(auth): Auth Emulator UI fix autofill

Fixes #386.

### CODE REVIEW

File: src/components/Auth/UserFormDialog/UserForm.tsx [hunk 1]
```diff
@@ -77,10 +77,12 @@ export const UserForm: React.FC<UserFormProps> = ({
 
       <form onSubmit={handleSubmit(submit)} data-testid="user-form">
         <DialogContent>
-          <Field
+          <FieldWithAutocompleteHack
             name="displayName"
             label="Display name (optional)"
             type="text"
+            setValue={form.setValue}
+            onChange={e => {}}
```
Comment (yuchenshi) [inline src/components/Auth/UserFormDialog/UserForm.tsx:85]:
```suggestion
```

**Review by yuchenshi — APPROVED** [review]
