### PR TITLE
Show empty document message and fix adding fields.

### LINKED ISSUE #437: api.tsx:51 Uncaught (in promise) Error: .set() on an existing document would delete other fields
Hi

Trying to add new data after deleting. This is more of an FYI & feedback.
-- This is from the Chrome console.

```
api.tsx:51 Uncaught (in promise) Error: .set() on an existing document would delete other fields
    at api.tsx:51
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

Restarting the server did not help.

Brad.

[firebase-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611359/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611360/firestore-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611361/ui-debug.log)
[database-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611362/database-debug.log)

### PR DESCRIPTION
**Pull request by yuchenshi**
Fixes #437.

### CODE REVIEW

File: src/components/Firestore/DocumentPreview/index.tsx [hunk 1]
```diff
@@ -101,6 +105,15 @@ const DocumentPreview: React.FC<Props> = ({
               </i>
             </Typography>
           )}
+          {docEmpty && (
+            <Typography
```
Comment (tjlav5) [inline src/components/Firestore/DocumentPreview/index.tsx:109]: Can we pull this out into a fn that :97 and this can both use?

**Review by tjlav5 — APPROVED** [review]

File: src/components/Firestore/DocumentPreview/index.tsx (hunk 1 above)
Comment (yuchenshi) [reply src/components/Firestore/DocumentPreview/index.tsx]: Done!
